# Generated by Django 6.0.2 on 2026-04-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_reader', '0002_pdfupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
