# Generated by Django 6.0.2 on 2026-04-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_reader', '0002_pdfupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('GR', 'Groceries'), ('GS', 'Gas'), ('PM', 'Payment'), ('SB', 'Subscription'), ('EN', 'Entertainment'), ('DF', 'Dining/Fast Food'), ('UT', 'Utilities'), ('FN', 'Furniture'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
