# Generated by Django 6.0.2 on 2026-04-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_reader', '0003_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='vendor_name',
            field=models.CharField(max_length=100),
        ),
    ]
