# Generated by Django 6.0.2 on 2026-04-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statement_reader', '0004_alter_transaction_vendor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('GR', 'Groceries'), ('GS', 'Gas'), ('PM', 'Payment'), ('SB', 'Subscription'), ('EN', 'Entertainment'), ('DF', 'Dining/Fast Food'), ('UT', 'Utilities'), ('FN', 'Furniture'), ('OT', 'Other')], default=None, max_length=2, null=True),
        ),
    ]
